// Pula celów do losowania na planszę. Edytuj tę listę — to domyślne źródło treści gry.
window.GOALS = [
  "Ktoś dosłownie staje z rozłożonymi rękami",
  "Afera plamowa",
  "Komisja Rewizyjna",
  "Dofinansowanie Krynicy",
  "„WSPÓLNOTA HUFCA”",
  "„Co z Jaworzem?”",
  "Remont dachu",
  "Odwołanie do polityków",
  "„Kończy się kadencja…”",
  "Naiwny Domirski",
  "Psioczenie na młodych",
  "Namiestnictwa",
  "Bałazy wszechwiedzący",
  "„Za moich czasów…”",
  "„Ja tylko krótko” — nie jest krótko",
  "Wniosek formalny z dupy",
  "Dyskusja o jednym słowie w uchwale",
  "„Czy możemy już głosować?”",
  "Ktoś zaczyna opowiadać historię sprzed 10+ lat",
  "Ktoś nie wie, nad czym właśnie głosujemy",
  "„Ale zawsze tak robiliśmy”",
  "Głosowanie tajne",
  "Jechanie po Kruczym",
  "Nowy hufiec",
  "Relacje w mieście",
];
