// Pula celów do losowania na planszę. Edytuj tę listę — to domyślne źródło treści gry.
window.GOALS = [
  "Znajdź 5 beboków",
  "Dowiedz się kiedy powstała Biblioteka Śląska",
  "Znajdź 3 murale",
  "Dowiedz się w jakim stylu został zbudowany kościół Mariacki",
  "Znajdź innych harcerzy",
  "Znajdź toaletę publiczną",
  "Znajdź 2 kobiety w czapkach i zapytaj je, co najbardziej lubią w Katowicach, a co im się nie podoba",
  "Znajdź sklep z produktem poniżej złotówki",
  "Znajdź 4 tramwaje o różnych numerach",
  "Znajdź dwie osoby z jedzeniem i zapytaj je, jaka jest ich ulubiona restauracja w Katowicach",
  "Znajdź herb lub logo Katowic",
  "Dowiedzcie się, ile miast graniczy z Katowicami",
  "Znajdź nowoczesny budynek stojący bezpośrednio obok starej, odrapanej kamienicy",
  "Znajdź 10 Żabek",
  "Zróbcie sobie zdjęcie pod palmami na rynku w Katowicach, udając że jesteście na egzotycznych wakacjach",
  "Zapytaj kogoś, gdzie jest najlepszy kebab w centrum Katowic, i się pod niego udajcie. Sprawdźcie, jaka jest najtańsza opcja kebaba",
  "Sprawdź, jaki pociąg odjeżdża pierwszy na dworcu",
  "Dowiedz się, co kiedyś znajdowało się na ul. Dworcowej zamiast banku PKO",
  "Znajdź dh Anię",
  "Poznajcie jedno nowe śląskie słowo",
  "Znajdź teatr i odwzoruj plakat jednej ze sztuk",
  "Znajdź ulicznego grajka",
  "Przejdź 2 km bez jechania autobusem",
  "Znajdź osobę, która mieszka ponad 40 lat w Katowicach",
  "Wygraj z obcą osobą w papier-kamień-nożyce",
];
